name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: dgknght/datomic-client
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: please01
          POSTGRES_USER: app_user
          POSTGRES_DB: xtdb_money_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      DB: '{:strategies {"sql" {:host "postgres"}}}'
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Setup MongoDB
        run: sudo docker run -d -p 27017:27017 mongo:6.0
      - name: Install dependencies
        run: lein deps
      - name: Migrate the SQL database
        run: lein with-profile dev,test migrate
      - name: Index the MongoDB database
        run: lein index-mongodb
      - name: Run tests
        run: lein test
